### ISSUE TITLE
What should be done to use the algorithm for IPv6 addresses?

### ISSUE THREAD

**Issue by highfei2011** [icehockeystar/botogon#1]
Hi, @icehockeystar

**Comment by highfei2011** [comment]
Have you solved this problem? Thank you.
[https://github.com/openstat/ip-radix-tree/issues/1](url)

**Comment by highfei2011** [comment]
Please, @icehockeystar

**Comment by icehockeystar** [comment]
@highfei2011 no I haven't.

**Comment by icehockeystar** [comment]
@highfei2011 in the end I didn't need it.

**Comment by highfei2011** [comment]
@icehockeystar Thanks, I have achieved![https://github.com/highfei2011/ip-radix-tree](https://github.com/highfei2011/ip-radix-tree)
